"""empty message

Revision ID: 506ac835d1c3
Revises: dc7ec82a6d2b
Create Date: 2019-03-23 21:55:44.215189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506ac835d1c3'
down_revision = 'dc7ec82a6d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profiles', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    # ### end Alembic commands ###
