"""empty message

Revision ID: 754e3e928bc3
Revises: 8ce85e66d132
Create Date: 2019-03-22 08:53:37.010487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754e3e928bc3'
down_revision = '8ce85e66d132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'filename')
    # ### end Alembic commands ###
